
load 'deploy'
# Uncomment if you are using Rails' asset pipeline
    # load 'deploy/assets'
load 'config/deploy' # remove this line to skip loading any of the default tasks
load 'config/drupal' # remove this line to skip loading any of the default tasks
role :web, "120.25.230.241"   # Your HTTP server, Apache/etc
set :application, "etoro"
set :branch,      "master"
set :deploy_to,   "/home/www/etoro"
set :deploy_via, :remote_cache

set :user,        "root"
set :use_sudo, false
ssh_options[:forward_agent] = true
ssh_options[:keys] = [File.join(ENV["HOME"], ".ssh", "keys/yeaoh")]
