<?php  
function elessons_permission_node_view($node, $view_mode, $langcode){

   if($node->type=="elesson"){
	
   global $user;

    $account = user_load($user->uid);

	 if(!empty($node->field_elessn_permission['und'][0]['tid']) && $node->field_elessn_permission['und'][0]['tid'] == 19){

	   return true;

	 }elseif(!empty($node->field_elessn_permission['und'][0]['tid']) && $node->field_elessn_permission['und'][0]['tid'] == 20){
		
		if($user->uid !=0){
		return true;
		}else{
		drupal_access_denied();
		exit;
		}
         }elseif(!empty($node->field_elessn_permission['und'][0]['tid']) && $node->field_elessn_permission['und'][0]['tid'] == 21){
		
   		if(!empty($account->field_practice_account_date['und'][0]['value']) && $account->field_practice_account_date['und'][0]['value']!=''){
			return true;
		}else{
		drupal_access_denied();
		exit;
		}

         }elseif(!empty($node->field_elessn_permission['und'][0]['tid']) && $node->field_elessn_permission['und'][0]['tid'] == 22){

   		if(!empty($account->field_ftd_date['und'][0]['value']) && $account->field_ftd_date['und'][0]['value']!=''){
			return true;
		}else{
		drupal_access_denied();
		exit;		
		}		
	 }else{
		return true;
	 }

   }

}

