<?php  
function elessons_permission_node_view($node, $view_mode, $langcode){

   if($node->type=="elesson"){
	
   global $user;

    $account = user_load($user->uid);


	 if(!empty($node->field_elessn_permission['und'][0]['tid']) && $node->field_elessn_permission['und'][0]['tid'] == 19){
	 	$values = array('title'=>'Local Site - Lesson - Page View','username'=>!empty($account->name) ? $account->name:t("normal account"),
                    'source_page_url'=>current_path());
      	mixpanel_track("user_lesson_view", $values);
	 	
	   return true;

	 }elseif(!empty($node->field_permission['und'][0]['tid']) && $node->field_permission['und'][0]['tid'] == 20){
		
		if($user->uid !=0){
			$values = array('title'=>'Local Site - Lesson - Page View','username'=>!empty($account->name) ? $account->name:t("normal account"),
                    'source_page_url'=>current_path());
      		mixpanel_track("user_lesson_view", $values);
			return true;
		}else{
		drupal_access_denied();
		exit;
		}
         }elseif(!empty($node->field_permission['und'][0]['tid']) && $node->field_permission['und'][0]['tid'] == 21){
		
   		if(!empty($account->field_practice_account_date['und'][0]['value']) && $account->field_practice_account_date['und'][0]['value']!=''){
   			$values = array('title'=>'Local Site - Lesson - Page View','username'=>!empty($account->name) ? $account->name:t("normal account"),
                    'source_page_url'=>current_path());
      		mixpanel_track("user_lesson_view", $values);
			return true;
		}else{
		drupal_access_denied();
		exit;
		}

         }elseif(!empty($node->field_permission['und'][0]['tid']) && $node->field_permission['und'][0]['tid'] == 22){

   		if(!empty($account->field_ftd_date['und'][0]['value']) && $account->field_ftd_date['und'][0]['value']!=''){
   			$values = array('title'=>'Local Site - Lesson - Page View','username'=>!empty($account->name) ? $account->name:t("normal account"),
                    'source_page_url'=>current_path());
      		mixpanel_track("user_lesson_view", $values);
			return true;
		}else{
		drupal_access_denied();
		exit;		
		}		
	 }else{
	 	$values = array('title'=>'Local Site - Lesson - Page View','username'=>!empty($account->name) ? $account->name:t("normal account"),
                    'source_page_url'=>current_path());
      	mixpanel_track("user_lesson_view", $values);
		return true;
	 }

   }

}


function elessons_permission_block_view_alter(&$data, $block){

  switch ($block->delta) {
    case 'outline':
       $data['content'] = overrite_outline();	
    break;
  }

}

function overrite_outline(){

$node = course_get_context();
  $item = ''; 
  if(isset($node->course['objects'])){
      $num = 1;
    foreach($node->course['objects'] as $courseObject ){
      $lessonid = $courseObject->instance;
      $lesson = node_load($lessonid);
     //$cid = $courseObject->coid;
       $title = '<div class="title">Course '.$num.': <a href="/node/'.$lesson->nid.'">'.$lesson->title.'</a></div>';

	$uri = !empty($lesson->field_image['und'][0]['uri'])?$lesson->field_image['und'][0]['uri']:'';
	$url = file_create_url($uri);
        $img =  '<img src="'.$url.'">';
	$item .= '<div class="item">'.$img.$title.'</div>';
      $num++;
    }
  }

 if($item!=''){
    return '<div id="items">'.$item.'</div><div class="control"><a  href="javascript:" id="prve"><img src="/sites/all/themes/Etoro/images/shang.png" /></a> <a href="javascript:" id="next"><img src="/sites/all/themes/Etoro/images/xia.png" /></a></div>';
 }else{
  return $item;
 }


}

