<?php

/**
 * @file
 * Allow users to login using an external email account.
 *
 * Users can login to the site using an IMAP/POP/NNTP server. If the email
 * address is associated with a Drupal user, that user is logged in. If not,
 * a new user is created.
 */

/**
 * Implements hook_menu().
 */
function pingan_login_menu() {
  $items['admin/config/people/pingan_login'] = array(
    'title' => 'Pingan Login',
    'description' => 'Pingan Login settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pingan_login_settings_form'),
    'access arguments' => array('administer users'),
    'file' => 'pingan_login.admin.inc',
  );

  $items['pingan_login/%/login'] = array(
    'title' => 'Pingan Login',
    'description' => 'Pingan Login page',
    'page callback' => 'pingan_login_login',
    'page arguments' => array(1),
    'access callback' => true,
    //'menu_name'=>'main-menu',
  );
  $items['pingan_login/callback'] = array(
    'title' => 'Pingan Login',
    'description' => 'Pingan Login page',
    'page callback' => 'pingan_login_callback',
    'access callback' => true,
   
  );
  $items['pingan_login/etoro_register'] = array(
    'title' => 'etoro Register',
    'description' => 'Pingan Login etoro Register',
    'page callback' => 'pingan_login_etoro_register',
    'access callback' => true,
    
  );
   $items['pingan_login/%/register'] = array(
    'title' => 'Pingan Login',
    'description' => 'Pingan Register page',
    'page arguments' => array(1),
    'page callback' => 'pingan_login_register',
    'access callback' => true,
    
  );

  return $items;
}

/**
* Implements hook_block_info().
*/
function pingan_login_block_info() {
  $blocks['pingan_login_box'] = array(
    'info' => t('Pingan Login block'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    
  );

  return $blocks;
}
 /**
* Implements hook_block_view().
*/
function pingan_login_block_view($delta = '') {
  global $user;
  $block = array();
  switch ($delta) {
    case 'pingan_login_box':
    drupal_add_css(drupal_get_path('module', "pingan_login") . "/css/pingan_login.css");
    drupal_add_js(drupal_get_path('module', "pingan_login") . "/js/pingan_login.js");
      $block['title'] = t('Do You Want to Learn More?');
      
      if($user->uid>0){
        $block['content'] = t('<p class="description">Register to access more materials</p>').t('Username').':'.$user->name.'  &nbsp; '.t('Email').':'.$user->mail;
      }else{
        $block['content'] = '<p class="description">Register to access more materials</p><div id="radius1"></div><button class="popLogin">'.t('Login').'</button> &nbsp; <button class="popRegister">'.t('Register').'</button><div id="radius"> </div><p class="gmpa"><a class="practice-account">Go to my pratice account</a></p><p class="opa"><a>Open practice account</a></p><div class="loginPop"><div class="popClose">Close</div><div class="popBody"><div class="titleLogin">'.t('Login').'</div><div class="titleRegister">'.t('Register').'</div><iframe width="660" style="border: 0;" height="650" src="" class="popSrc"></iframe></div></div>';
      }
      
      break;
  }
  return $block;
}

/**
  * login page
  */
function pingan_login_login($type=""){

$time=date("Y-m-d h:i:s");
header("Location: ".($type=="mobile" ? variable_get('pingan_login_mobile_url'):variable_get('pingan_login_pc_url'))."?appId=".variable_get('pingan_appid')."&timestamp=".$time."&signature=".md5("etoroappId=".variable_get('pingan_appid')."&timestamp=".$time."etoro").($type=="mobile" ? "&paramType=app":"")."&signtype=MD5");
}
/**
  * register page
  */
function pingan_login_register($type=""){
$time=date("Y-m-d h:i:s");

header("Location: ".($type=="mobile" ? variable_get('pingan_register_mobile_url'):variable_get('pingan_register_pc_url'))."?appId=".variable_get('pingan_appid')."&withMobile=1&timestamp=".$time."&signature=".md5("etoroappId=".variable_get('pingan_appid')."&timestamp=".$time."&withMobile=1etoro").($type=="mobile" ? "&paramType=app":"")."&signtype=MD5");

}

/**
  * ping an  callback function 
  */
function pingan_login_etoro_register(){
  global $user;
  $userBirthdate="";
if($user->field_toaid['und'][0]['value']!=""){
  $userBirthdate=date("[d, m, Y]",strtotime($user->field_toaid['und'][0]['value']));
}

  echo '<html><head>
<script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
<script src="http://184.170.226.76/js/production/modularRegistration.min.js"></script>
<!--<script src="https://register.etoro.com/js/production/modularRegistration.min.js"></script>-->
<script>
RegistrationService({
"isDebug":false,
"loadCSS":true,
},
function(T){
var registration=new T.RegistrationService.Registration({
"container":"#form",
"version":"ver16",
"culture":"zh-cn",
"checkUserIP":false,
"socialConnect":false,
"funnelFromID":12,
"successRedirect":false,
"funnelID":12,  
"overriddenValues":{"toa_id": "'.$user->field_toaid['und'][0]['value'].'",
       "gender": "'.$user->field_gender['und'][0]['value'].'",
       "birth_date": "'.$userBirthdate.'",
       "toaPhone": "'.$user->field_toaphone['und'][0]['value'].'",
       "is_toa_phone_verified": true,
       "toaFullname": "'.$user->field_toafullname['und'][0]['value'].'",
       "chinese_id_number": "'.$user->field_chineseidnumber['und'][0]['value'].'",
       "chinese_id_type": "'.$user->field_chineseidtype['und'][0]['value'].'"
      }  
});  

registration.on("after:render", function (event) {}); 
registration.on("before:render", function (event) {});
registration.on("on:submit", function (event) {}); 
registration.on("on:error", function (event) {
  $("#regbox").html("'.t("注册失败，网络连接错误。请联系管理员。").'")
}); 
registration.on("on:success", function (event) {
$("#regbox").html(\'<div style="text-align:center">'.t('注册成功，欢迎您成为etoro会员').'</div><br><input type="button" value="'.t('跳转到etoro会员中心').'" onclick="https://www.baidu.com"> <input type="button" value="'.t('关闭窗口').'" onclick="window.parent.location.reload();">\')

}); 
registration.show();
});
</script>
</head>
<body>
<div id="regbox">
<form id="form"></form>
</div>
</body>
</html>
';
  exit;
}
/**
  * ping an  callback function 
  */
function pingan_login_callback(){
 // print_r($_REQUEST);
  
  $requestxml=decrypt($_REQUEST['3desAssert'],variable_get('pingan_key'));
  //print_r($requestxml);exit;
  $xmlObject = simplexml_load_string($requestxml);
//print_r($xmlObject);exit;
  if($xmlObject->result=="00"){

    $userdata=array('name'=>(string)$xmlObject->attributes->attribute[0]['value'],
    'phone'=>(string)$xmlObject->attributes->attribute[1]['value'],
    'mail'=>(string)$xmlObject->attributes->attribute[2]['value'],
    'sex'=>(string)$xmlObject->attributes->attribute[3]['value'],
    'idNo'=>(string)$xmlObject->attributes->attribute[4]['value'],
    'idType'=>(string)$xmlObject->attributes->attribute[5]['value'],
    'birthDate'=>(string)$xmlObject->attributes->attribute[6]['value'],
    'cnName'=>(string)$xmlObject->attributes->attribute[7]['value'],
    'customerLevel'=>(string)$xmlObject->attributes->attribute[8]['value'],
    'toaId'=>(string)$xmlObject->subject,
    'openid'=>md5('etoro'.(string)$xmlObject->attributes->attribute[1]['value'].'etoro'));
      $userid=db_query("SELECT `entity_id` FROM `field_data_field_pingan_openid` WHERE `field_pingan_openid_value`='".$userdata['openid']."'")->fetchField();
          if(empty($userid) || $userid==""){
              $name=$userdata['name'];
              $account = array(
                  'name' =>$name,
                  'pass' => '',
                  'mail' => $userdata['mail'],
                  'status' => 1,
                  'init' => $name,
                  'roles' => 2
              );
              $userReg=user_save(null, $account);
              $account=user_load($userReg->uid);
              $edit=array();
              $edit['field_pingan_openid']['und'][0]['value']=$userdata['openid'];
              $edit['field_first_name']['und'][0]['value']=!empty($userdata['cnName']) ? substr($userdata['cnName'],1,5):"";
              $edit['field_last_name']['und'][0]['value']=!empty($userdata['cnName']) ? substr($userdata['cnName'],1,5):"";
              $edit['field_gender']['und'][0]['value']=!empty($userdata['sex']) ? $userdata['sex']:"";
              $edit['field_type_of_id']['und'][0]['value']=!empty($userdata['customerLevel']) ? $userdata['customerLevel']:"";
              $edit['field_date_of_birth']['und'][0]['value']=!empty($userdata['birthDate']) ? $userdata['birthDate']:"";
              $edit['field_toaid']['und'][0]['value']=!empty($userdata['toaId']) ? $userdata['toaId']:"";
              $edit['field_toafullname']['und'][0]['value']=!empty($userdata['cnName']) ? $userdata['cnName']:"";
              $edit['field_toaphone']['und'][0]['value']=!empty($userdata['phone']) ? $userdata['phone']:"";
              $edit['field_istoaphoneverified']['und'][0]['value']=1;
              $edit['field_chineseidnumber']['und'][0]['value']=!empty($userdata['idNo']) ? $userdata['idNo']:"";
              $edit['field_chineseidtype']['und'][0]['value']=!empty($userdata['idType']) ? $userdata['idType']:"";

              user_save($account, $edit);
             
            $isReg=1;
           
         }else{
           $isReg=0;
          $account=user_load($userid);
          if(count($userdata)>2){
            $edit=array();
           
              $edit['field_pingan_openid']['und'][0]['value']=$userdata['openid'];
              $edit['field_first_name']['und'][0]['value']=!empty($userdata['cnName']) ? substr($userdata['cnName'],1,5):"";
              $edit['field_last_name']['und'][0]['value']=!empty($userdata['cnName']) ? substr($userdata['cnName'],1,5):"";
              $edit['field_gender']['und'][0]['value']=!empty($userdata['sex']) ? $userdata['sex']:"";
              $edit['field_type_of_id']['und'][0]['value']=!empty($userdata['customerLevel']) ? $userdata['customerLevel']:"";
              $edit['field_date_of_birth']['und'][0]['value']=!empty($userdata['birthDate']) ? $userdata['birthDate']:"";
              $edit['field_toaid']['und'][0]['value']=!empty($userdata['toaId']) ? $userdata['toaId']:"";
              $edit['field_toafullname']['und'][0]['value']=!empty($userdata['cnName']) ? $userdata['cnName']:"";
              $edit['field_toaphone']['und'][0]['value']=!empty($userdata['phone']) ? $userdata['phone']:"";
              $edit['field_istoaphoneverified']['und'][0]['value']=1;
              $edit['field_chineseidnumber']['und'][0]['value']=!empty($userdata['idNo']) ? $userdata['idNo']:"";
              $edit['field_chineseidtype']['und'][0]['value']=!empty($userdata['idType']) ? $userdata['idType']:"";

              user_save($account, $edit);
            }    
         }
        if ($account) {
          global $user;

          // Call logout hooks.
          module_invoke_all('user_logout', $user);

          // Switching user.
          $user = $account;
          drupal_session_regenerate();

          // Call all login hooks.
          $edit = array();
          user_module_invoke('login', $edit, $user);
        }
        echo '<div class="success_msg">';
        if($isReg){
          echo '<div style="text-align:center">'.t('注册成功，欢迎您成为etoro中国会员').'</div><br><input type="button" value="'.t('跳转到etoro注册').'" onclick="/pingan_login/etoro_register"> <input type="button" value="'.t('关闭窗口').'" onclick="window.parent.location.reload();">';
        }else{
          echo t('登陆成功，请关闭窗口。系统将在3s内关闭窗口<br>').'<script type="text/javascript">setTimeout("window.parent.location.reload()",3000);</script>';
        }
        echo '</div>';
        //drupal_goto("/user");

    }else{
      echo '<div class="error_msg">'.t('登陆失败，请联系管理员。<br>错误信息:').$xmlObject->message.' '.$xmlObject->message.'</div>';
     
    }
     exit;
    
}

/*pingan 3des decode*/
function decrypt($encrypted,$key) { //  
    $encrypted = base64_decode ($encrypted ); 
    $key = str_pad ( $key, 24, '0' ); 
    $td = mcrypt_module_open ( MCRYPT_3DES, '', 'ecb', '' ); 
    $iv = @mcrypt_create_iv ( mcrypt_enc_get_iv_size ( $td ), MCRYPT_RAND ); 
    $ks = mcrypt_enc_get_key_size ( $td ); 
    @mcrypt_generic_init ( $td, $key, $iv ); 
    $decrypted = mdecrypt_generic ( $td, $encrypted ); 
    mcrypt_generic_deinit ( $td ); 
    mcrypt_module_close ( $td ); 
    $y = pkcs5_unpad ( $decrypted ); 
    $code=urldecode(base64_decode($y));
    return $code; 
} 

function pkcs5_unpad($text) { 
    $pad = ord ( $text {strlen ( $text ) - 1} ); 
    if ($pad > strlen ( $text )) { 
        return false; 
    } 
    if (strspn ( $text, chr ( $pad ), strlen ( $text ) - $pad ) != $pad) { 
        return false; 
    } 
    return substr ( $text, 0, - 1 * $pad ); 
} 

function xml_to_array( $xml )
{
    $reg = "/<(\\w+)[^>]*?>([\\x00-\\xFF]*?)<\\/\\1>/";
    if(preg_match_all($reg, $xml, $matches))
    {
        $count = count($matches[0]);
        $arr = array();
        for($i = 0; $i < $count; $i++)
        {
            $key= $matches[1][$i];
            $val = xml_to_array( $matches[2][$i] );  // 递归
            if(array_key_exists($key, $arr))
            {
                if(is_array($arr[$key]))
                {
                    if(!array_key_exists(0,$arr[$key]))
                    {
                        $arr[$key] = array($arr[$key]);
                    }
                }else{
                    $arr[$key] = array($arr[$key]);
                }
                $arr[$key][] = $val;
            }else{
                $arr[$key] = $val;
            }
        }
        return $arr;
    }else{
        return $xml;
    }
}

?>
