<?php


function MFT_Course_menu() {
  $items['admin/config/etoro/MFT_Course'] = array(
    'title' => 'MFT_Course',
    'description' => 'MFT_Course settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('MFT_Course_settings_form'),
    'access arguments' => array('administer users'),
    'file' => 'MFT_Course.admin.inc',
  );
 return $items;
}


 function MFT_Course_node_view($node,$view_mode,$langcode) {


    if ($node->type=="elesson"){
       global $language;
       if($language->prefix == "en"){
            if($node->field_type ==null){
                   return;
             }

            if(isset($node->field_type['und']['0']['tid'])){
             $term = taxonomy_term_load($node->field_type['und']['0']['tid']);   
             $term = i18n_taxonomy_localize_terms($term);
            if($term->name =="eVideo"){
                      
                 
                  
                   if($node->field_course_id == null || $node->field_lesson_id == null){
                      return;
                    }else{
                   $courseid = $node->field_course_id['und']['0']['value'];
                   $lessonid = $node->field_lesson_id['und']['0']['value'];
                   $lsns = "";
                   if(isset($node->field_sequence['und']['0']['value'])){
                   $lsns = $node->field_sequence['und']['0']['value'];
                    }
                   //echo '<pre>';
                  //print_r($node->field_video_type['und']['0']['value']);exit;
                   //print_r($node->field_lesson_id); exit; 
                 if (isset($node->field_video_type['und']['0']['value'])&&$node->field_video_type['und']['0']['value'] == "key1"){
                               $text = variable_get('vodevideo'); 
                        }else{
                  $text = variable_get('evideo');
                                }
                  $replace_course = str_replace('courseid',$courseid,$text);
                  $replace_lesson = str_replace('lessonid',$lessonid,$replace_course);
                  $replace_language = str_replace('language','en',$replace_lesson);
                  $replace_lsns = str_replace('sequence',$lsns, $replace_language);
                  $output ="$replace_lsns";
		//$node->field_lesson_id['video'] = array(
		   //'#markup' => $output,
 		   //'#weight'=>-1,
		// );
                      $node->content['field_lesson_id'][0]['#markup'] = $output;
                 }
              
           }
         }
              if(isset($node->field_type['und']['0']['tid'])){
               $term = taxonomy_term_load($node->field_type['und']['0']['tid']); 
               	$term = i18n_taxonomy_localize_terms($term);
              if($term->name =="eBook"){
                //echo '<pre>';
                //print_r($node->field_book_id); exit; 
                if($node->field_course_id == null){
                return;
                        }
                else{
                $courseid = $node->field_course_id['und']['0']['value'];
                  $text = variable_get('ebook');

                  $replace_course = str_replace('courseid',$courseid,$text);
                  $replace_language = str_replace('language','en',$replace_course);
                $output ="$replace_language";
		//$node->content['book'] = array(
		   //'#markup' => $output,
 		   //'#weight'=>-1,
		// );
                    $node->content['field_lesson_id'][0]['#markup'] = $output;    
                }
           }
       }
        }elseif ($language->prefix == "cn"){
              if($node->field_type ==null){
                return;
              }
              if(isset($node->field_type['und']['0']['tid'])){
               $term = taxonomy_term_load($node->field_type['und']['0']['tid']); 
               	$term = i18n_taxonomy_localize_terms($term);
              if($term->name =="电子视频"){

                  
                
                 if($node->field_course_id == null || $node->field_lesson_id == null){
                               return;
                              }
                   else{
                   $courseid = $node->field_course_id['und']['0']['value'];
                   $lessonid = $node->field_lesson_id['und']['0']['value'];
              
                   $lsns = "";
                   if(isset($node->field_sequence['und']['0']['value'])){
                   $lsns = $node->field_sequence['und']['0']['value'];
                    }


                  if (isset($node->field_video_type['und']['0']['value'])&&$node->field_video_type['und']['0']['value'] == "key1"){
                               $text = variable_get('vodevideo'); 
                        }else{
                  $text = variable_get('evideo');
                                }

                  $replace_course = str_replace('courseid',$courseid,$text);
                  $replace_lesson = str_replace('lessonid',$lessonid,$replace_course);
                  $replace_language = str_replace('language','cn',$replace_lesson);
                  $replace_lsns = str_replace('sequence',$lsns, $replace_language);
                  $output ="$replace_lsns";
		//$node->content['video'] = array(
		  // '#markup' => $output,
 		   //'#weight'=>-1,
		// );  
                       $node->content['field_lesson_id'][0]['#markup'] = $output;   
                  }
               
              }
           }
           if(isset($node->field_type['und']['0']['tid'])){
           $term = taxonomy_term_load($node->field_type['und']['0']['tid']); 
           	$term = i18n_taxonomy_localize_terms($term);
            if($term->name =="电子书"){
                 
                    if($node->field_course_id ==null){
                               return;
                              }
                    else{
                    $courseid = $node->field_course_id['und']['0']['value'];
                     $text = variable_get('ebook');
                     $replace_course = str_replace('courseid',$courseid,$text);
                     
                     $replace_language = str_replace('language','cn',$replace_course);
                    $output ="$replace_language";
		    //$node->content['book'] = array(
		   //'#markup' => $output,
 		   //'#weight'=>-1,
		   // );
                      $node->content['field_lesson_id'][0]['#markup'] = $output;
                }
          }
        }
      }

    }
}


