<?php


 function MFT_Course_node_view($node,$view_mode,$langcode) {

    if ($node->type=="elesson"){
       global $language;
       if($language->language == "en"){
        
            if($node->field_type['und']['0']['taxonomy_term']->name =="eVideo"){
                   
                   $courseid = $node->field_course_id['und']['0']['value'];
                   $lessonid = $node->field_lesson_id['und']['0']['value'];
                   //echo '<pre>';
                   //print_r($courseid);
                   //print_r($lessonid); exit;   
                 $output ="<iframe allowfullscreen frameborder=0 src='//www.mte-media.com/admin2/frames/put_course.php?prd=tls&lng=cn&ref=83462ba&set=Default' width='100%' height='800px' ></iframe>";
		
		 $node->content['video'] = array(
		   '#markup' => $output,
 		   '#weight'=>-1,
		 );

		

                 }

       }
    }
}
